/******************************************************************************
* Filename: WebDBContextLocal.cs
* Project:  UTC
* 
* Description:
* Local implementation of WebDBContext class additions not generated by SQLMETAL
* 
* Revision History:
* $Log: /MonstersUnlimited/utc/unitethiscity.com/website/App_Code/WebDBContextLocal.cs $
 * 
 * 1     1/13/13 9:19p Mterry
 * merge object dev
******************************************************************************/
using System.Web.Configuration;

/// <summary>
/// Local implementation of WebDBContext class additions not generated by SQLMETAL
/// </summary>
public partial class WebDBContext : System.Data.Linq.DataContext
{
	public WebDBContext()
		: this( WebConfigurationManager.ConnectionStrings[ "WebDBConnectionString" ].ConnectionString )
	{
	}
}