/******************************************************************************
 * Filename: WebDBContext.cs
 * Project:  UTC WebAPI
 * 
 * Description:
 * SQLMETAL database context access code.  Rest of class is generated using
 * the DOSQLMETAL batch file.
******************************************************************************/
using System.Web.Configuration;

namespace com.unitethiscity.api.Models
{
    /// <summary>
    /// Local implementation of WebDBContext class additions not generated by SQLMETAL
    /// </summary>
    public partial class WebDBContext : System.Data.Linq.DataContext
    {
        public WebDBContext()
            : this(WebConfigurationManager.ConnectionStrings["WebDBConnectionString"].ConnectionString)
        {
        }
    }
}